//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::asset_designateds::Entity as AssetDesignateds;
pub use super::asset_documents::Entity as AssetDocuments;
pub use super::assets::Entity as Assets;
pub use super::designateds::Entity as Designateds;
pub use super::notes::Entity as Notes;
pub use super::users::Entity as Users;
